version: '3'
services:
  # Database Service. We use PostgreSQL from official postgres library
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      # There you can map local folder for DB files
      - ./database:/var/lib/postgresql/data
  # Prisma Service from official prisma library
  prisma:
    image: prismagraphql/prisma:1.26
    restart: always
    ports:
      - 4466:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: database
            port: 5432
            user: postgres
            password: password
            migrations: true
